## DNS server
apiVersion: v1
kind: Service
metadata:
  name: dns
  namespace: infra
spec:
  selector:
    func: dns
  clusterIP: 10.96.100.254
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
    - name: dns-udp
      protocol: UDP
      port: 53
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-dns
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      func: dns
  template:
    metadata:
      labels:
        func: dns
    spec:
      hostname: dns
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      dnsConfig:
        nameservers:
          - 127.0.0.1
      containers:
      - name: dns
        image: gabbro:30500/cdn-dns:cps-0.1
        imagePullPolicy: Never
        env:
        - name: MY_SERVICE_IP
          value: '10.96.100.254'
        ports:
        - containerPort: 53
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
        envFrom:
          - configMapRef:
              name: cdn-config
