apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: cdn-pv
spec:
  capacity:
    storage: "64Gi"
  accessModes:
    - "ReadWriteMany"
  nfs:
    path: "/full/path/of/nfs/dir"
    server: NFS_SERVER_ENDPOINT
