## Enroller
apiVersion: v1
kind: Service
metadata:
  name: enroller
  namespace: infra
spec:
  selector:
    func: enroll
## somehow no port exposing in docker-compose file
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-enroller
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      func: enroll
  template:
    metadata:
      labels:
        func: enroll
    spec:
      hostname: enroller
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.96.100.254
        searches:
          - infra.ciab.test
          - ciab.test
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      containers:
      - name: enroller
        image: gabbro:30500/cdn-enroller:cps-0.1
        imagePullPolicy: Never
        env:
        - name: MY_SERVICE_IP
          value: $(ENROLLER_SERVICE_HOST)
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
        envFrom:
          - configMapRef:
              name: cdn-config
---
##OPS DB
apiVersion: v1
kind: Service
metadata:
  name: db 
  namespace: infra
spec:
  selector:
    func: db
    role: ops
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-ops-db
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      func: db
      role: ops
  template:
    metadata:
      labels:
        func: db
        role: ops
    spec:
      hostname: db
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.96.100.254
        searches:
          - infra.ciab.test
          - ciab.test
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      - name: postgres-data
        emptyDir: {}
      containers:
      - name: ops-db
        image: gabbro:30500/cdn-ops-db:cps-0.1
        imagePullPolicy: Never
        env:
        - name: MY_SERVICE_IP
          value: $(DB_SERVICE_HOST)
        ports:
        - containerPort: 5432
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
          - mountPath: /var/lib/postgresql/data
            name: postgres-data
        envFrom:
          - configMapRef:
              name: cdn-config
---
#operation(API) servers: Perl and Go
apiVersion: v1
kind: Service
metadata:
  name: trafficops-perl
  namespace: infra
spec:
  selector:
    func: ops
    lang: perl
  ports:
    - port: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-ops-perl
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      func: ops
      lang: perl
  template:
    metadata:
      labels:
        func: ops
        lang: perl
    spec:
      hostname: trafficops-perl
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.96.100.254
        searches:
          - infra.ciab.test
          - ciab.test
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      - name: ops-ca
        persistentVolumeClaim:
          claimName: cdn-ops-ca
      containers:
      - name: ops-perl
        image: gabbro:30500/cdn-ops-perl:cps-0.1
        imagePullPolicy: Never
        env:
        - name: MY_SERVICE_IP
          value: $(TRAFFICOPS_PERL_SERVICE_HOST)
        ports:
        - containerPort: 443
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
          - mountPath: /ca
            name: ops-ca
        envFrom:
          - configMapRef:
              name: cdn-config
---
apiVersion: v1
kind: Service
metadata:
  name: trafficops
  namespace: infra
spec:
  selector:
    func: ops
    lang: go
  ports:
    - port: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-ops
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      func: ops
      lang: go
  template:
    metadata:
      labels:
        func: ops
        lang: go
    spec:
      hostname: trafficops
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.96.100.254
        searches:
          - infra.ciab.test
          - ciab.test
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      containers:
      - name: ops-go
        image: gabbro:30500/cdn-ops-go:cps-0.1
        imagePullPolicy: Never
        env:
        - name: MY_SERVICE_IP
          value: $(TRAFFICOPS_SERVICE_HOST)        
        ports:
        - containerPort: 443
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
        envFrom:
          - configMapRef:
              name: cdn-config
