## DNS server
apiVersion: v1
kind: Service
metadata:
  name: dns
spec:
  selector:
    func: dns
  clusterIP: 10.99.0.254
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
#      port: 9353
#      targetPort: 53
    - name: dns-udp
      protocol: UDP
      port: 53
#      port: 9353
#      targetPort: 53
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      func: dns
  template:
    metadata:
      labels:
        func: dns
    spec:
      hostname: dns
      subdomain: infra
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      dnsPolicy: ClusterFirst
      dnsConfig:
        nameservers:
          - 127.0.0.1
        searches:
          - ciab.test    
      containers:
      - name: dns
        image: gabbro:30500/cdn-dns
        imagePullPolicy: Never
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
        envFrom:
          - configMapRef:
              name: cdn-config
---
apiVersion: v1
kind: Service
metadata:
  name: ops-db 
spec:
  selector:
    func: db
    role: ops
  clusterIP: 10.99.0.10
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-ops-db
spec:
  replicas: 1
  selector:
    matchLabels:
      func: db
      role: ops
  template:
    metadata:
      labels:
        func: db
        role: ops
    spec:
      hostname: db
      subdomain: infra
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      - name: postgres-data
        emptyDir: {}
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.99.0.254
        searches:
          - ciab.test    
      containers:
      - name: ops-db
        image: gabbro:30500/cdn-ops-db
        imagePullPolicy: Never
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
          - mountPath: /var/lib/postgresql/data
            name: postgres-data
        envFrom:
          - configMapRef:
              name: cdn-config
---
## Enroller
apiVersion: v1
kind: Service
metadata:
  name: enroller
spec:
  selector:
    func: enroll
  clusterIP: 10.99.0.200
## somehow no port exposing in docker-compose file
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-enroller
spec:
  replicas: 1
  selector:
    matchLabels:
      func: enroll
  template:
    metadata:
      labels:
        func: enroll
    spec:
      hostname: enroller
      subdomain: infra
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.99.0.254
        searches:
          - ciab.test    
      containers:
      - name: enroller
        image: gabbro:30500/cdn-enroller
        imagePullPolicy: Never
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
        envFrom:
          - configMapRef:
              name: cdn-config
---
#vault: create credentials
apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  selector:
    func: secret
  clusterIP: 10.99.0.50
## not sure what these ports for..
  ports:
    - name: port1
      port: 8087
    - name: port2
      port: 8098
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-traffic-vault
spec:
  replicas: 1
  selector:
    matchLabels:
      func: secret
  template:
    metadata:
      labels:
        func: secret
    spec:
      hostname: trafficvault
      subdomain: infra
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      - name: schema
        emptyDir: {}
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.99.0.254
        searches:
          - ciab.test    
      containers:
      - name: vault
        image: gabbro:30500/cdn-vault
        imagePullPolicy: Never
        env:
        - name: CLUSTER_NAME
          value: trafficvault
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
          - mountPath: /etc/riak/schemas
            name: schema
        envFrom:
          - configMapRef:
              name: cdn-config
---
#states manager

#operation(API) servers: Perl and Go
apiVersion: v1
kind: Service
metadata:
  name: ops-perl
spec:
  selector:
    func: ops
    lang: perl
  clusterIP: 10.99.0.21
  ports:
    - port: 443 #6443
#      targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-ops-perl
spec:
  replicas: 1
  selector:
    matchLabels:
      func: ops
      lang: perl
  template:
    metadata:
      labels:
        func: ops
        lang: perl
    spec:
      hostname: trafficops-perl
      subdomain: infra
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      - name: ops-ca
        persistentVolumeClaim:
          claimName: cdn-ops-ca
      - name: schema
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.99.0.254
        searches:
          - ciab.test    
      containers:
      - name: ops-perl
        image: gabbro:30500/cdn-ops-perl
        imagePullPolicy: Never
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
          - mountPath: /ca
            name: ops-ca
        envFrom:
          - configMapRef:
              name: cdn-config
---
apiVersion: v1
kind: Service
metadata:
  name: ops-go
spec:
  selector:
    func: ops
    lang: go
  clusterIP: 10.99.0.20
  ports:
    - port: 443 #6443
#      targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      func: ops
      lang: go
  template:
    metadata:
      labels:
        func: ops
        lang: go
    spec:
      hostname: trafficops
      subdomain: infra
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.99.0.254
        searches:
          - ciab.test    
      containers:
      - name: ops-go
        image: gabbro:30500/cdn-ops-go
        imagePullPolicy: Never
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
        envFrom:
          - configMapRef:
              name: cdn-config
#Mock origin server

#Router

#Monitor

#Portal
